fix: downloader worker stand alone (#91)
* fix: remove internal router

* feat: check health status of workers

* feat: logger debug

* refactor: queues logic in server-core

* fix: movie player

* fix: movie settings download button work with waiting

* feat: subtitles download

* feat: sse for movie state

* fix: seed + movie player progress bar

* fix: DownloadStates

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -123,6 +123,16 @@ jobs:
           kill $LOGS_PID
           exit 1
 
+      - name: Check all containers status
+        run: |
+          for container in $(docker ps --format "{{.Names}}"); do
+            status=$(docker inspect --format='{{.State.Status}}' $container 2>/dev/null || echo "not found")
+            if [ "$status" != "running" ]; then
+              echo "❌ $container is not running"
+              exit 1
+            fi
+          done
+
       - name: Shutdown all containers
         if: always()
         run: |
